baseURL = "https://passi0n1.github.io/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
title = "Passi0n1's Blog"
copyright = "Rise. 本站遵循 CC-BY-NC 4.0 协议"
theme = "diary"

# Generate sitemap in the public folder
[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "世界是我们的游乐场."


enableGiscus = true
[params.giscus]
    data_repo="Passi0n1/passi0n1.github.io"
    data_repo_id="R_kgDOOOjm3g"    
    data_category="Announcements"
    data_category_id="DIC_kwDOOOjm3s4Coczr"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="en"
    crossorigin="anonymous"

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 3


[markup.goldmark.renderer]
    unsafe = true



# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "abcdefghzd"

# Google Analytics
[services]
  [services.googleAnalytics]
    id = "G-ESWXK6HG1Q"  

