
backend:
  name: github
  repo: Passi0n1/passi0n1.github.io
  branch: main
  auth_type: implicit
  app_id: Ov23liHqiffFjcge1u0l

media_folder: ""
collections:
  - name: "test"
    label: "测试"
    folder: "_posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }